version: '3'

services:

  proxy:
    image: traefik
    command: --docker
    ports:
      - "1082:80"     # The HTTP port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - proxy

networks:
  proxy:
    external: true
