version: '3'
services:

    mysql:
        image: mysql:5.7
        environment:
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_ROOT_PASSWORD=test
        network_mode: "host"
